fix compile errors from new compiler
Using the v20210106, got around 1000 errors. Added goog.require statements and changed
to use the short name instead of the fully qualified path name. Most of the errors were
like this:
src/lab/controls/CheckBoxControl.js:26:11: ERROR - [JSC_MISSING_REQUIRE_TYPE]
'myphysicslab.lab.util.ParameterBoolean' references a fully qualified namespace, which
is disallowed by the style guide.
Please add a goog.requireType, assign or destructure it into an alias, and use the
alias instead.
  26| * @param {!myphysicslab.lab.util.ParameterBoolean} parameter
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Had to add more goog.forwardDeclare() statements in various places.